name: baithi
description: Flutter Chat App - Firebase Auth & Firestore
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0


  # UI
  cupertino_icons: ^1.0.6

  # State
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.1
  
  # Media
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  path_provider: ^2.1.3
  provider: ^6.0.5
  # Emoji (BẢN MỚI – FIX XUNG ĐỘT)
  emoji_picker_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
